//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JhankaulSainik.AppResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JhankaulSainik.AppResource.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Jhankaul.
        /// </summary>
        internal static string AddJhankaul {
            get {
                return ResourceManager.GetString("AddJhankaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New About.
        /// </summary>
        internal static string AddNewAbout {
            get {
                return ResourceManager.GetString("AddNewAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Admit Card.
        /// </summary>
        internal static string AddNewAdmitCard {
            get {
                return ResourceManager.GetString("AddNewAdmitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New All Students.
        /// </summary>
        internal static string AddNewAllStudent {
            get {
                return ResourceManager.GetString("AddNewAllStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Chief Guest.
        /// </summary>
        internal static string AddNewChiefGuest {
            get {
                return ResourceManager.GetString("AddNewChiefGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sainik.
        /// </summary>
        internal static string AddNewSainik {
            get {
                return ResourceManager.GetString("AddNewSainik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Organizers.
        /// </summary>
        internal static string AddOrganizers {
            get {
                return ResourceManager.GetString("AddOrganizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Prizes.
        /// </summary>
        internal static string AddPrizes {
            get {
                return ResourceManager.GetString("AddPrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Results.
        /// </summary>
        internal static string AddResults {
            get {
                return ResourceManager.GetString("AddResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add School.
        /// </summary>
        internal static string AddSchool {
            get {
                return ResourceManager.GetString("AddSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admit Card.
        /// </summary>
        internal static string AdmitCard {
            get {
                return ResourceManager.GetString("AdmitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Students.
        /// </summary>
        internal static string AllStudents {
            get {
                return ResourceManager.GetString("AllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Guest.
        /// </summary>
        internal static string ChiefGuest {
            get {
                return ResourceManager.GetString("ChiefGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Organizers.
        /// </summary>
        internal static string DetailsOrganizers {
            get {
                return ResourceManager.GetString("DetailsOrganizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Prizes.
        /// </summary>
        internal static string DetailsPrizes {
            get {
                return ResourceManager.GetString("DetailsPrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Profile.
        /// </summary>
        internal static string DetailsProfile {
            get {
                return ResourceManager.GetString("DetailsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Result.
        /// </summary>
        internal static string DetailsResult {
            get {
                return ResourceManager.GetString("DetailsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details School.
        /// </summary>
        internal static string DetailsSchool {
            get {
                return ResourceManager.GetString("DetailsSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sainik.
        /// </summary>
        internal static string EditSainik {
            get {
                return ResourceManager.GetString("EditSainik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        internal static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Id.
        /// </summary>
        internal static string FacebookId {
            get {
                return ResourceManager.GetString("FacebookId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        internal static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Year.
        /// </summary>
        internal static string InvitationYear {
            get {
                return ResourceManager.GetString("InvitationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jhankaul.
        /// </summary>
        internal static string Jhankaul {
            get {
                return ResourceManager.GetString("Jhankaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Chief Guest Data.
        /// </summary>
        internal static string NoChiefGuestData {
            get {
                return ResourceManager.GetString("NoChiefGuestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organizer Data.
        /// </summary>
        internal static string NoOrganizerData {
            get {
                return ResourceManager.GetString("NoOrganizerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अब ऐप अंग्रेजी में.
        /// </summary>
        internal static string NowAppInEnglish {
            get {
                return ResourceManager.GetString("NowAppInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अब ऐप हिंदी में.
        /// </summary>
        internal static string NowAppInHindi {
            get {
                return ResourceManager.GetString("NowAppInHindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizers.
        /// </summary>
        internal static string Organizers {
            get {
                return ResourceManager.GetString("Organizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post In Army.
        /// </summary>
        internal static string PostInArmy {
            get {
                return ResourceManager.GetString("PostInArmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post In Office.
        /// </summary>
        internal static string PostInOffice {
            get {
                return ResourceManager.GetString("PostInOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prizes.
        /// </summary>
        internal static string Prizes {
            get {
                return ResourceManager.GetString("Prizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sainik.
        /// </summary>
        internal static string Sainik {
            get {
                return ResourceManager.GetString("Sainik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sainik View Details.
        /// </summary>
        internal static string SainikViewDetails {
            get {
                return ResourceManager.GetString("SainikViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update About.
        /// </summary>
        internal static string UpdateAbout {
            get {
                return ResourceManager.GetString("UpdateAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Admit Card.
        /// </summary>
        internal static string UpdateAdmitCard {
            get {
                return ResourceManager.GetString("UpdateAdmitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All Students.
        /// </summary>
        internal static string UpdateAllStudents {
            get {
                return ResourceManager.GetString("UpdateAllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Chief Guest.
        /// </summary>
        internal static string UpdateChiefGuest {
            get {
                return ResourceManager.GetString("UpdateChiefGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Jhankaul.
        /// </summary>
        internal static string UpdateJhankaul {
            get {
                return ResourceManager.GetString("UpdateJhankaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Organizers.
        /// </summary>
        internal static string UpdateOrganizers {
            get {
                return ResourceManager.GetString("UpdateOrganizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Prizes.
        /// </summary>
        internal static string UpdatePrizes {
            get {
                return ResourceManager.GetString("UpdatePrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Results.
        /// </summary>
        internal static string UpdateResults {
            get {
                return ResourceManager.GetString("UpdateResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Sainik.
        /// </summary>
        internal static string UpdateSainik {
            get {
                return ResourceManager.GetString("UpdateSainik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update School.
        /// </summary>
        internal static string UpdateSchool {
            get {
                return ResourceManager.GetString("UpdateSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year From.
        /// </summary>
        internal static string YearFrom {
            get {
                return ResourceManager.GetString("YearFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year To.
        /// </summary>
        internal static string YearTo {
            get {
                return ResourceManager.GetString("YearTo", resourceCulture);
            }
        }
    }
}
